
; /* Start:"a:4:{s:4:"full";s:100:"/bitrix/templates/acrit-studio-2023/components/hipot/includer/index_page/script.min.js?1689260182936";s:6:"source";s:82:"/bitrix/templates/acrit-studio-2023/components/hipot/includer/index_page/script.js";s:3:"min";s:0:"";s:3:"map";s:0:"";}"*/
$(function(){$("#owl-portfolio").owlCarousel({items:4,loop:true,margin:10,dots:false,nav:true,navElement:"div",navText:['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>'],autoHeight:true,lazyLoad:false,responsive:{0:{items:1},480:{items:2},768:{items:3},1e3:{items:4}},onInitialized:function(){$("#owl-portfolio").css("display","block")},onRefreshed:function(){lazyLoadInstance.update()}});function runAnimatedBlocks(){const blocks=document.querySelectorAll(".animated-block");function showBlocks(){const trigger=window.innerHeight/10*9;blocks.forEach(block=>{const topOfBlock=block.getBoundingClientRect().top;if(topOfBlock<trigger){block.classList.add("animation-active")}})}window.addEventListener("scroll",showBlocks);showBlocks()}runAnimatedBlocks();$(".map_index").on("click",function(){$(this).find("iframe").addClass("clicked")}).on("mouseleave",function(){$(this).find("iframe").removeClass("clicked")})});
/* End */
;
; /* Start:"a:4:{s:4:"full";s:93:"/bitrix/templates/acrit-studio-2023/js/lite-youtube-embed/lite-yt-embed.min.js?16895322932869";s:6:"source";s:74:"/bitrix/templates/acrit-studio-2023/js/lite-youtube-embed/lite-yt-embed.js";s:3:"min";s:0:"";s:3:"map";s:0:"";}"*/
class LiteYTEmbed extends HTMLElement{connectedCallback(){this.videoId=this.getAttribute("videoid");let playBtnEl=this.querySelector(".lty-playbtn");this.playLabel=playBtnEl&&playBtnEl.textContent.trim()||this.getAttribute("playlabel")||"Play";if(!this.style.backgroundImage){this.style.backgroundImage=`url("https://i.ytimg.com/vi/${this.videoId}/hqdefault.jpg")`}if(!playBtnEl){playBtnEl=document.createElement("button");playBtnEl.type="button";playBtnEl.classList.add("lty-playbtn");this.append(playBtnEl)}if(!playBtnEl.textContent){const playBtnLabelEl=document.createElement("span");playBtnLabelEl.className="lyt-visually-hidden";playBtnLabelEl.textContent=this.playLabel;playBtnEl.append(playBtnLabelEl)}playBtnEl.removeAttribute("href");this.addEventListener("pointerover",LiteYTEmbed.warmConnections,{once:true});this.addEventListener("click",this.addIframe);this.needsYTApiForAutoplay=navigator.vendor.includes("Apple")||navigator.userAgent.includes("Mobi")}static addPrefetch(kind,url,as){const linkEl=document.createElement("link");linkEl.rel=kind;linkEl.href=url;if(as){linkEl.as=as}document.head.append(linkEl)}static warmConnections(){if(LiteYTEmbed.preconnected)return;LiteYTEmbed.addPrefetch("preconnect","https://www.youtube-nocookie.com");LiteYTEmbed.addPrefetch("preconnect","https://www.google.com");LiteYTEmbed.addPrefetch("preconnect","https://googleads.g.doubleclick.net");LiteYTEmbed.addPrefetch("preconnect","https://static.doubleclick.net");LiteYTEmbed.preconnected=true}fetchYTPlayerApi(){if(window.YT||window.YT&&window.YT.Player)return;this.ytApiPromise=new Promise((res,rej)=>{var el=document.createElement("script");el.src="https://www.youtube.com/iframe_api";el.async=true;el.onload=_=>{YT.ready(res)};el.onerror=rej;this.append(el)})}async addYTPlayerIframe(params){this.fetchYTPlayerApi();await this.ytApiPromise;const videoPlaceholderEl=document.createElement("div");this.append(videoPlaceholderEl);const paramsObj=Object.fromEntries(params.entries());new YT.Player(videoPlaceholderEl,{width:"100%",videoId:this.videoId,playerVars:paramsObj,events:{onReady:event=>{event.target.playVideo()}}})}async addIframe(){if(this.classList.contains("lyt-activated"))return;this.classList.add("lyt-activated");const params=new URLSearchParams(this.getAttribute("params")||[]);params.append("autoplay","1");params.append("playsinline","1");if(this.needsYTApiForAutoplay){return this.addYTPlayerIframe(params)}const iframeEl=document.createElement("iframe");iframeEl.width=560;iframeEl.height=315;iframeEl.title=this.playLabel;iframeEl.allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture";iframeEl.allowFullscreen=true;iframeEl.src=`https://www.youtube-nocookie.com/embed/${encodeURIComponent(this.videoId)}?${params.toString()}`;this.append(iframeEl);iframeEl.focus()}}customElements.define("lite-youtube",LiteYTEmbed);
/* End */
;; /* /bitrix/templates/acrit-studio-2023/components/hipot/includer/index_page/script.min.js?1689260182936*/
; /* /bitrix/templates/acrit-studio-2023/js/lite-youtube-embed/lite-yt-embed.min.js?16895322932869*/
